Repository orbit-1690/scouting2020, pull requests merged in 2020-02, with the labels that each got.

#44 nicer font
  src/Climbing.elm
Labels: bug

#83 nicer colors
  src/Autonomous.elm
  src/Climbing.elm
  src/Colors.elm
  src/ScoutingMain.elm
  src/TeamData.elm
  src/Teleop.elm
Labels: enhancement

#103 make counter buttons wider
  src/Counter.elm
Labels: enhancement

#104 Remove arrows' background
  src/ScoutingMain.elm
Labels: nice to have
